version: '2'

services:
    db:
        image: mysql
        command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf3
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: ./php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - /projects/sfcourse:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
            - ./php7-fpm/php-timezone.ini:/usr/local/etc/php/conf.d/docker-php-timezone.ini
    nginx:
        build: ./nginx
        ports:
            - 8888:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
